name: Aperture
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3297
title: Aperture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73960401-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
