name: Aperture
favicon: null
layout_spectrum: 0.5008041695691645
typography_spectrum: 0.20156502141617239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12391180568374693
  lightness: 0.10589331644587219
  saturation: 0.7932607114780694
  rhythmicContrast: 0.24514535861089826
purpose: []
